src/apps/get_in_touch/urls.py
from django.conf.urls import urlfrom . import views, views_ajaxurlpatterns = [    url(r'^upload/$', views_ajax.UploadView.as_view(), name='upload'),    url(r'^$', views.IndexView.as_view(), name='index'),]

src/project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.http import Http404

from admin_honeypot.admin import honeypot_site
from libs.autoslug import ALIAS_REGEXP
from main import views as main_views
from contacts import views as contact_views
from .sitemaps import site_sitemaps


def root_router(request, *args, **kwargs):
    """
        Роутер для страниц вида /slug/
    """
    from products.models import ProductCategory, Product
    from products.views import CategoryView, DetailView

    slug = kwargs.get('slug')
    if ProductCategory.objects.filter(slug=slug).exists():
        return CategoryView.as_view()(request, *args, **kwargs)
    elif Product.objects.filter(slug=slug).exists():
        return DetailView.as_view()(request, *args, **kwargs)
    else:
        raise Http404


urlpatterns = [
    url(r'^admin/', include(honeypot_site.urls)),
    url(r'^dladmin/social/', include('social_networks.admin_urls', namespace='admin_social_networks')),
    url(r'^dladmin/autocomplete/', include('libs.autocomplete.urls', namespace='autocomplete')),
    url(r'^dladmin/ckeditor/', include('ckeditor.admin_urls', namespace='admin_ckeditor')),
    url(r'^dladmin/gallery/', include('gallery.admin_urls', namespace='admin_gallery')),
    url(r'^dladmin/users/', include('users.admin_urls', namespace='admin_users')),
    url(r'^dladmin/ctr/', include('admin_ctr.urls', namespace='admin_ctr')),
    url(r'^dladmin/', include(admin.site.urls)),

    url(r'^$', main_views.IndexView.as_view(), name='index'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
    url(r'^500/$', 'django.views.defaults.server_error'),
    url(r'^away/$', 'libs.away.views.away', name='away'),
    url(r'^jsi18n/$', 'project.views.cached_javascript_catalog', name='jsi18n'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': site_sitemaps}),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': site_sitemaps}),

    url(r'^ckeditor/', include('ckeditor.urls', namespace='ckeditor')),
    url(r'^blocks/', include('attachable_blocks.urls', namespace='blocks')),
    url(r'^placeholder/', include('placeholder.urls', namespace='placeholder')),
    url(r'^social/', include('social_networks.urls', namespace='social_networks')),
    url(r'^rating/', include('rating.urls', namespace='rating')),

    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^support-and-discover/', include('support.urls', namespace='support')),
    url(r'^media/', include('media.urls', namespace='media')),
    url(r'^where-to-buy/', include('where_to_buy.urls', namespace='where_to_buy')),
    url(r'^open-a-business-account/', include('business_account.urls', namespace='business_account')),
    url(r'^employment-opportunities-retailer/', include('employment_opportunities.urls', namespace='employment_opportunities')),
    url(r'^contact/', include('contacts.urls', namespace='contacts')),

    url(r'^thank-you/$', contact_views.ThanksView.as_view(), name='thanks'),

    url(r'^get_in_touch/', include('get_in_touch.urls', namespace='get_in_touch')),

    url(r'^(?P<slug>{})/$'.format(ALIAS_REGEXP), root_router, name='root_router'),
]


if settings.DEBUG:
    urlpatterns += [
        # Для доступа к MEDIA-файлам при разработке
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.STATIC_ROOT}
        ),
    ]

src/apps_common/gallery/models.py
import os
from django.db import models
from django.core import checks
from django.conf import settings
from django.utils.timezone import now
from django.db.models.functions import Coalesce
from django.contrib.contenttypes import generic
from django.core.exceptions import ValidationError
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _, ungettext
from django.contrib.contenttypes.models import ContentType
from model_utils.managers import InheritanceQuerySetMixin
from libs.upload import upload_file, URLError
from libs.storages.media_storage import MediaStorage
from libs.aliased_queryset import AliasedQuerySetMixin
from libs.videolink_field.fields import VideoLinkField
from libs.variation_field.utils import is_size, check_variations, format_variations
from .fields import GalleryImageField, GalleryVideoLinkPreviewField

__all__ = ('GalleryBase', 'GalleryItemBase', 'GalleryImageItem', 'GalleryVideoLinkItem')


MAX_SIZE_DEFAULT = getattr(settings,  'GALLERY_MAX_SIZE_DEFAULT', 15*1024*1024)
MIN_DIMENSIONS_DEFAULT = getattr(settings,  'GALLERY_MIN_DIMENSIONS_DEFAULT', (0, 0))
MAX_DIMENSIONS_DEFAULT = getattr(settings,  'GALLERY_MAX_DIMENSIONS_DEFAULT', (6000, 6000))
MAX_SOURCE_DIMENSIONS_DEFAULT = getattr(settings,  'GALLERY_MAX_SOURCE_DIMENSIONS_DEFAULT', (3072, 3072))
ADMIN_CLIENT_RESIZE_DEFAULT = getattr(settings,  'GALLERY_ADMIN_CLIENT_RESIZE_DEFAULT', False)


class GalleryItemQuerySet(InheritanceQuerySetMixin, AliasedQuerySetMixin, models.QuerySet):
    """ QuerySet элемента галереи """
    def aliases(self, qs, kwargs):
        """ Добавляем возможность фильтровать по конктерной модели элемента """
        model = kwargs.pop('model', None)
        if model is not None:
            ct = ContentType.objects.get_for_model(model, for_concrete_model=False)
            qs &= models.Q(self_type=ct)
        return qs

    def _filter_or_exclude(self, *args, **kwargs):
        """ Возвращаем реальные классы элементов галерей при фильтрации """
        return super()._filter_or_exclude(*args, **kwargs).select_subclasses()


class GalleryItemBase(models.Model):
    """ Базовый класс элемента галереи """
    _cache = {}

    # Форма, использующаяся для задания описания и т.п.
    EDIT_FORM = 'gallery.forms.GalleryItemBaseForm'

    # Имена полей, чьи значения копируются при клонировании элемента
    COPY_FIELDS = set()

    self_type = models.ForeignKey(ContentType, editable=False, related_name='+')
    content_type = models.ForeignKey(ContentType)
    object_id = models.IntegerField()
    gallery = generic.GenericForeignKey(for_concrete_model=False)
    description = models.TextField(_('description'), blank=True)

    sort_order = models.PositiveIntegerField(_('sort order'), default=0)
    created = models.DateTimeField(_('created on'), blank=True)
    changed = models.DateTimeField(_('changed on'), auto_now=True)

    objects = GalleryItemQuerySet.as_manager()

    class Meta:
        verbose_name = _('gallery item')
        verbose_name_plural = _('gallery items')
        ordering = ('object_id', 'sort_order', 'created', )
        index_together = (('content_type', 'object_id'), )
        default_permissions = ()

    def save(self, *args, **kwargs):
        is_add = not self.pk
        if is_add:
            self.self_type = ContentType.objects.get_for_model(type(self), for_concrete_model=False)
            self.created = now()

            self.sort_order = self.gallery.items.aggregate(
                max=Coalesce(models.Max('sort_order'), 0) + 1
            )['max']

        super().save(*args, **kwargs)

    @classmethod
    def check(cls, **kwargs):
        errors = super().check(**kwargs)
        errors.extend(cls._check_copy_fields(**kwargs))
        return errors

    @classmethod
    def _check_copy_fields(cls, **kwargs):
        if not isinstance(cls.COPY_FIELDS, set):
            return [
                checks.Error(
                    'COPY_FIELDS should be an instance of set',
                    obj=cls
                )
            ]
        else:
            return []

    @property
    def is_image(self):
        return isinstance(self, GalleryImageItem)

    @property
    def is_video_link(self):
        return isinstance(self, GalleryVideoLinkItem)

    @property
    def admin_show_url(self):
        """
            Ссылка на просмотр в админке
        """
        return ''

    def after_copy(self, **kwargs):
        """
            Пост-обработка скопированного элемента.
            Параметр self - это уже новый элемент.
        """
        pass


def generate_filepath(instance, filename):
    """ Генерация пути сохранения файла """
    return instance.generate_filename(os.path.basename(filename))


class GalleryImageItem(GalleryItemBase):
    """ Элемент-картинка галереи """
    _cache = {}

    EDIT_FORM = 'gallery.forms.GalleryImageItemForm'

    COPY_FIELDS = GalleryItemBase.COPY_FIELDS | {'image_crop', }

    # Корневая папка (storage)
    STORAGE_LOCATION = None

    # Границы размеров картинок, при превышении которых вызывается ошибка валидации
    MIN_DIMENSIONS = MIN_DIMENSIONS_DEFAULT
    MAX_DIMENSIONS = MAX_DIMENSIONS_DEFAULT

    # Приблизительный размер, к которому приводятся исходники картинок
    MAX_SOURCE_DIMENSIONS = MAX_SOURCE_DIMENSIONS_DEFAULT

    # Максимальный вес картинок
    MAX_SIZE = MAX_SIZE_DEFAULT

    # Уменьшать картинку до размера MAX_SOURCE_DIMENSIONS в админке на клиенте
    ADMIN_CLIENT_RESIZE = ADMIN_CLIENT_RESIZE_DEFAULT

    # Качество исходника в случае, когда он сохраняется через PIL
    SOURCE_QUALITY = 90

    # Качество картинок вариаций по умолчанию
    DEFAULT_QUALITY = 85

    # Имя вариации, которая используется для полноэкранного просмотра картинки в админке.
    # Если указан None - будет ссылка на исходник
    SHOW_VARIATION = ''

    # Имя вариации, которая показывается в админке
    ADMIN_VARIATION = ''

    # Аспекты, используемые плагином Jcrop в админке.
    # Вещественное число / имя вариации / кортеж вещественных чисел / кортеж имен вариаций.
    ASPECTS = ()

    # Вариации, на которые нарезаются картинки.
    VARIATIONS = {}

    # =============================================================================

    image = GalleryImageField(_('image'),
        storage=MediaStorage(),
        upload_to=generate_filepath,
        crop_field='image_crop',
    )
    image_crop = models.CharField(_('stored_crop'),
        max_length=32,
        blank=True,
        editable=False,
    )
    image_alt = models.CharField(_('alt'), blank=True, max_length=255)

    class Meta:
        verbose_name = _('image item')
        verbose_name_plural = _('image items')
        ordering = ('object_id', 'sort_order', 'created',)
        default_permissions = ()
        abstract = True

    def __init__(self, *args, **kwargs):
        field = self._meta.get_field('image')
        if self.STORAGE_LOCATION:
            field.storage.set_directory(self.STORAGE_LOCATION)
        super().__init__(*args, **kwargs)

    def __str__(self):
        return _('Image item %(pk)s (%(path)s)') % {'pk': self.pk or 'None', 'path': self.image}

    @classmethod
    def check(cls, **kwargs):
        errors = super().check(**kwargs)
        errors.extend(cls._check_storage_location(**kwargs))
        errors.extend(cls._check_min_dimensions(**kwargs))
        errors.extend(cls._check_max_dimensions(**kwargs))
        errors.extend(cls._check_max_source_dimensions(**kwargs))
        errors.extend(cls._check_variations(**kwargs))
        errors.extend(cls._check_aspects(**kwargs))
        errors.extend(cls._check_show_variation(**kwargs))
        errors.extend(cls._check_admin_variation(**kwargs))
        return errors

    @classmethod
    def _check_storage_location(cls, **kwargs):
        if not cls.STORAGE_LOCATION:
            return [
                checks.Error(
                    'STORAGE_LOCATION is required',
                    obj=cls
                )
            ]
        elif not isinstance(cls.STORAGE_LOCATION, str):
            return [
                checks.Error(
                    'STORAGE_LOCATION must be an instance of str',
                    obj=cls
                )
            ]
        else:
            return []

    @classmethod
    def _check_min_dimensions(cls, **kwargs):
        if not cls.MIN_DIMENSIONS:
            return [
                checks.Error(
                    'MIN_DIMENSIONS is required',
                    obj=cls
                )
            ]
        elif not is_size(cls.MIN_DIMENSIONS):
            return [
                checks.Error(
                    'MIN_DIMENSIONS must be a tuple of 2 non-negative numbers',
                    obj=cls
                )
            ]
        else:
            return []

    @classmethod
    def _check_max_dimensions(cls, **kwargs):
        if not cls.MAX_DIMENSIONS:
            return [
                checks.Error(
                    'MAX_DIMENSIONS is required',
                    obj=cls
                )
            ]
        elif not is_size(cls.MAX_DIMENSIONS):
            return [
                checks.Error(
                    'MAX_DIMENSIONS must be a tuple of 2 non-negative numbers',
                    obj=cls
                )
            ]
        else:
            return []

    @classmethod
    def _check_max_source_dimensions(cls, **kwargs):
        if not cls.MAX_SOURCE_DIMENSIONS:
            return [
                checks.Error(
                    'MAX_SOURCE_DIMENSIONS is required',
                    obj=cls
                )
            ]
        elif not is_size(cls.MAX_SOURCE_DIMENSIONS):
            return [
                checks.Error(
                    'MAX_SOURCE_DIMENSIONS must be a tuple of 2 non-negative numbers',
                    obj=cls
                )
            ]
        else:
            return []

    @classmethod
    def _check_variations(cls, **kwargs):

src/apps_common/gallery/forms.py
from django import forms
from libs.form_helper.forms import FormHelperMixin
from .models import GalleryItemBase, GalleryImageItem


class GalleryItemBaseForm(FormHelperMixin, forms.ModelForm):
    csrf_token = False

    class Meta:
        model = GalleryItemBase
        fields = (
            'description',
        )
        widgets = {
            'description': forms.Textarea(attrs={
                'rows': 5,
            })
        }


class GalleryImageItemForm(FormHelperMixin, forms.ModelForm):
    csrf_token = False

    class Meta:
        model = GalleryImageItem
        fields = (
            'image_alt', 'description',
        )
        widgets = {
            'description': forms.Textarea(attrs={
                'rows': 5,
            })
        }

src/apps_common/gallery/templates/gallery/admin/form.html
<form>
  {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {{ field }}
    </div>
  {% endfor %}
</form>

src/apps_common/gallery/templates/gallery/admin/gallery.html
{% load i18n %}

<style>
  #add_id_{{ name }} {
    display: none;
  }

  #gallery-{{ name }} .gallery-item {
    width: {{ admin_item_size.0 }}px;
    height: {{ admin_item_size.1 }}px;
  }
</style>

<script>
  var admin_gallery_create = "{% url 'admin_gallery:create' %}";
  var admin_gallery_delete = "{% url 'admin_gallery:delete' %}";
  var admin_gallery_upload = "{% url 'admin_gallery:upload' %}";
  var admin_gallery_upload_video = "{% url 'admin_gallery:upload_video' %}";
  var admin_gallery_sort = "{% url 'admin_gallery:sort' %}";
  var admin_gallery_delete_item = "{% url 'admin_gallery:delete_item' %}";
  var admin_gallery_rotate_item = "{% url 'admin_gallery:rotate_item' %}";
  var admin_gallery_crop_item = "{% url 'admin_gallery:crop_item' %}";
  var admin_gallery_edit_item = "{% url 'admin_gallery:edit_item' %}";
</script>

{% block gallery %}
  <div class="gallery gallery-standart" id="gallery-{{ name }}"
      data-applabel="{{ app_label }}"
      data-modelname="{{ model_name }}">

    {% block content %}
      <input type="hidden" class="gallery_id" {{ attrs }} value="{{ gallery.pk|default:"" }}"/>
      <input type="hidden" class="max_item_count" value="{{ gallery_model.MAX_ITEM_COUNT|default:0 }}"/>

      {% if gallery_model.IMAGE_MODEL %}
        <input type="hidden" class="aspects" value="{{ image_aspects }}">
        <input type="hidden" class="min_dimensions" value="{{ image_min_dimensions }}">
        <input type="hidden" class="max_dimensions" value="{{ image_max_dimensions }}">
        <input type="hidden" class="max_size" value="{{ image_max_size }}">
        <input type="hidden" class="max_source" value="{{ image_max_source }}">
      {% endif %}

      <div class="gallery-wrapper">
        {% if gallery %}
          {% include gallery_model.ADMIN_TEMPLATE_ITEMS %}
        {% else %}
          {% include gallery_model.ADMIN_TEMPLATE_EMPTY %}
        {% endif %}
      </div>

      <!-- templates -->
      <script type="text/template" class="image-template">
        <div class="gallery-item gallery-item-image"
             style="width:{{ admin_item_size.0 }}px; height:{{ admin_item_size.1 }}px;">

          <a target="_blank" class="item-preview" style="display:none;">
            <img src=""/>
          </a>

          <div class="item-preloader">
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0"
                   aria-valuemax="100"></div>
            </div>
          </div>

          <span class="item-controls">
            <input type="checkbox" name="gallery-item" class="check-box" value="">
            <a class="icon-edit item-crop" title="{% trans 'Crop image' %}"></a>
            <a class="icon-repeat item-rotate-left"
               title="{% trans 'Rotate by 90 degrees counterclockwise' %}"></a>
            <a class="icon-repeat item-rotate-right"
               title="{% trans 'Rotate by 90 degrees clockwise' %}"></a>
            <a class="icon-pencil item-form" title="{% trans 'Edit item' %}"></a>
            <a class="icon-trash item-delete" title="{% trans 'Delete' %}"></a>
          </span>
        </div>
      </script>

      <script type="text/template" class="videolink-template">
        <div class="gallery-item gallery-item-video-link">

          <a target="_blank" class="item-preview" style="display:none;">
            <span class="inner">
              <img src=""/>
            </span>
          </a>

          <div class="item-preloader"></div>

          <span class="item-controls">
            <input type="checkbox" class="check-box" value="">
            <a class="icon-pencil item-form" title="{% trans 'Edit item' %}"></a>
            <a class="icon-trash item-delete" title="{% trans 'Delete' %}"></a>
          </span>
        </div>
      </script>
    {% endblock content %}

  </div>
{% endblock gallery %}

src/apps_common/gallery/templates/gallery/admin/gallery_empty.html
{% load i18n %}

{% block buttons %}
  <button class="btn btn-success create-gallery">{% trans 'Create gallery' %}</button>
{% endblock buttons %}

src/apps_common/gallery/templates/gallery/admin/gallery_items.html
{% load i18n %}

<div class="caption">
  {% if gallery_model.VIDEO_LINK_MODEL %}
    {% blocktrans with image_count=gallery.image_items.count video_count=gallery.video_link_items.count count counter=image_count %}
      Gallery has <span class="gallery-image-counter">{{ image_count }}</span> image and
      <span class="gallery-videolink-counter">{{ video_count }}</span> video
    {% plural %}
      Gallery has <span class="gallery-image-counter">{{ image_count }}</span> images and
      <span class="gallery-videolink-counter">{{ video_count }}</span> video
    {% endblocktrans %}
  {% else %}
    {% blocktrans with image_count=gallery.image_items.count count counter=image_count %}
      Gallery has <span class="gallery-image-counter">{{ image_count }}</span> image
    {% plural %}
      Gallery has <span class="gallery-image-counter">{{ image_count }}</span> images
    {% endblocktrans %}
  {% endif %}
</div>

<div class="gallery-items" id="gallery-{{ name }}-items">
  {% for item in gallery.all_items %}
    {% if item.is_image %}
      <div class="gallery-item gallery-item-image" data-id="{{ item.id }}"
          {% if item.image %}
           data-source_url="{{ item.image.url }}"
           data-source_size="{{ item.image.dimensions|join:',' }}"
          {% endif %}>

        <a {% if item.admin_show_url %}href="{{ item.admin_show_url }}"{% endif %} target="_blank" class="item-preview">
          <img src="{{ item.admin_variation.url }}">
        </a>

        <span class="item-controls">
          <input type="checkbox" class="check-box" value="{{ item.id }}">
          <a class="icon-edit item-crop" title="{% trans 'Crop image' %}" data-crop="{{ item.image.croparea }}"></a>
          <a class="icon-repeat item-rotate-left"
             title="{% trans 'Rotate by 90 degrees counterclockwise' %}"></a>
          <a class="icon-repeat item-rotate-right" title="{% trans 'Rotate by 90 degrees clockwise' %}"></a>
          <a class="icon-pencil item-form" title="{% trans 'Edit item' %}"></a>
          <a class="icon-trash item-delete" title="{% trans 'Delete' %}"></a>
        </span>
      </div>
    {% elif item.is_video_link %}
      <div class="gallery-item gallery-item-video-link" data-id="{{ item.id }}">
        <a href="{{ item.admin_show_url }}" target="_blank" class="item-preview">
          <span class="inner">
            <img src="{{ item.admin_variation.url }}">
          </span>
        </a>

        <span class="item-controls">
          <input type="checkbox" class="check-box" value="{{ item.id }}">
          <a class="icon-pencil item-form" title="{% trans 'Edit item' %}"></a>
          <a class="icon-trash item-delete" title="{% trans 'Delete' %}"></a>
        </span>
      </div>
    {% endif %}
  {% endfor %}
</div>

{% block buttons %}
  <div class="buttons clearfix">
    <div style="float: left">
      {% if gallery.IMAGE_MODEL %}
        <button class="btn btn-success add-gallery-image">
          <i class="icon-folder-open icon-white"></i>
          {% trans 'Add image' %}
        </button>
      {% endif %}

      {% if gallery.VIDEO_LINK_MODEL %}
        <button class="btn btn-success add-gallery-video">
          {% trans 'Add video' %}
        </button>
      {% endif %}
    </div>
    <div style="float: right">
      <button class="btn btn-danger delete-checked-items"
              disabled="disabled">{% trans 'Delete checked items' %}</button>
      <button class="btn btn-danger delete-gallery">{% trans 'Delete gallery' %}</button>
    </div>
  </div>
{% endblock buttons %}

<div class="dragover-content">
  <span>{% trans 'Drop files here' %}</span>
</div>